// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADqzu9QKtTYHRqvOM84OD1Nb1rX_pi84c',
    appId: '1:801858899837:web:41ffcc11a3ca324750c614',
    messagingSenderId: '801858899837',
    projectId: 'oauth-454eb',
    authDomain: 'oauth-454eb.firebaseapp.com',
    storageBucket: 'oauth-454eb.firebasestorage.app',
    measurementId: 'G-WS2PMVDM8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3jknjm4vYlFBUzavKCPgYvsBAiyOtICQ',
    appId: '1:801858899837:android:b769be4ba1d5087250c614',
    messagingSenderId: '801858899837',
    projectId: 'oauth-454eb',
    storageBucket: 'oauth-454eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4oC25PE3jVBOWkRyhexV1RK9ZG9SFF08',
    appId: '1:801858899837:ios:d7849806d07d2e5a50c614',
    messagingSenderId: '801858899837',
    projectId: 'oauth-454eb',
    storageBucket: 'oauth-454eb.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4oC25PE3jVBOWkRyhexV1RK9ZG9SFF08',
    appId: '1:801858899837:ios:d7849806d07d2e5a50c614',
    messagingSenderId: '801858899837',
    projectId: 'oauth-454eb',
    storageBucket: 'oauth-454eb.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADqzu9QKtTYHRqvOM84OD1Nb1rX_pi84c',
    appId: '1:801858899837:web:e29fd8258d172d2c50c614',
    messagingSenderId: '801858899837',
    projectId: 'oauth-454eb',
    authDomain: 'oauth-454eb.firebaseapp.com',
    storageBucket: 'oauth-454eb.firebasestorage.app',
    measurementId: 'G-YMWBJ7YSWH',
  );

}