import 'package:client/pages/login.dart';
import 'package:client/pages/register.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';

// Firebase imports
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'NextChamp Fitness',
      debugShowCheckedModeBanner: false,
      
      // --- FIXED: Modern ThemeData with ColorScheme ---
      theme: ThemeData(
        brightness: Brightness.dark,
        fontFamily: 'Roboto',
        scaffoldBackgroundColor: Colors.black,

        // Define a ColorScheme. This is the recommended way to set theme colors.
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFD0FD3E), // Your main brand color
          brightness: Brightness.dark,
          primary: const Color(0xFFD0FD3E), // Explicitly set the primary color
          background: Colors.black,
        ),

        // This ensures ElevatedButton uses the primary color from the ColorScheme
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFFD0FD3E), // Your primary color
            foregroundColor: Colors.black, // Text color on the button
          ),
        ),
      ),
      // --- END OF FIX ---
      
      home: const WelcomePage(),
    );
  }
}

class WelcomePage extends StatelessWidget {
  const WelcomePage({super.key});

  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);

    return Scaffold(
      body: Stack(
        fit: StackFit.expand,
        children: [
          Image.asset('assets/backround.png', fit: BoxFit.cover),
          Container(
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  Color(0xCC000000), // 80% opaque black
                  Color(0x99000000), // 60% opaque black
                  Colors.transparent
                ],
                begin: Alignment.bottomCenter,
                end: Alignment.topCenter,
              ),
            ),
          ),
          SafeArea(
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 20.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    padding: const EdgeInsets.all(8),
                    decoration: const BoxDecoration(
                      color: Color(0xE6FFFFFF), // 90% opaque white
                      shape: BoxShape.circle,
                    ),
                    child: const Icon(Icons.sports_gymnastics, color: Colors.black, size: 24),
                  ),
                  const Spacer(),
                  const Text(
                    'TRAIN\nRECORD\nACHIEVE',
                    style: TextStyle(color: Colors.white, fontSize: 38, fontWeight: FontWeight.bold, height: 1.2),
                  ),
                  const SizedBox(height: 30),
                  Row(
                    children: [
                      Expanded(
                        child: ElevatedButton(
                          onPressed: () {
                            Navigator.push(context, MaterialPageRoute(builder: (context) => const RegisterPage()));
                          },
                          // This button will now correctly use the theme's primary color
                          style: ElevatedButton.styleFrom(
                            padding: const EdgeInsets.symmetric(vertical: 18),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(50)),
                          ),
                          child: const Text('Join Now', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                        ),
                      ),
                      const SizedBox(width: 15),
                      Expanded(
                        child: ElevatedButton(
                          onPressed: () {
                            Navigator.push(context, MaterialPageRoute(builder: (context) => const LoginPage()));
                          },
                          // Style for the secondary button
                          style: ElevatedButton.styleFrom(
                            backgroundColor: const Color(0x33FFFFFF), // 20% opaque white
                            foregroundColor: Colors.white,
                            padding: const EdgeInsets.symmetric(vertical: 18),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(50)),
                          ),
                          child: const Text('Log In', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}